package top.winxblast.happymall.pojo;

import java.util.Date;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_category.id
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_category.parent_id
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_category.name
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_category.status
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_category.sort_order
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_category.create_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_category.update_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happymall_category
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Category(Integer id, Integer parentId, String name, Boolean status, Integer sortOrder, Date createTime, Date updateTime) {
        this.id = id;
        this.parentId = parentId;
        this.name = name;
        this.status = status;
        this.sortOrder = sortOrder;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happymall_category
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Category() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_category.id
     *
     * @return the value of happymall_category.id
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_category.id
     *
     * @param id the value for happymall_category.id
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_category.parent_id
     *
     * @return the value of happymall_category.parent_id
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_category.parent_id
     *
     * @param parentId the value for happymall_category.parent_id
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_category.name
     *
     * @return the value of happymall_category.name
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_category.name
     *
     * @param name the value for happymall_category.name
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_category.status
     *
     * @return the value of happymall_category.status
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_category.status
     *
     * @param status the value for happymall_category.status
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_category.sort_order
     *
     * @return the value of happymall_category.sort_order
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_category.sort_order
     *
     * @param sortOrder the value for happymall_category.sort_order
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_category.create_time
     *
     * @return the value of happymall_category.create_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_category.create_time
     *
     * @param createTime the value for happymall_category.create_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_category.update_time
     *
     * @return the value of happymall_category.update_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_category.update_time
     *
     * @param updateTime the value for happymall_category.update_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Category category = (Category) o;

        return id != null ? id.equals(category.id) : category.id == null;
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}