package top.winxblast.happymall.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_user.id
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_user.username
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_user.password
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_user.email
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_user.phone
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_user.question
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_user.answer
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_user.role
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_user.create_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column happymall_user.update_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happymall_user
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public User(Integer id, String username, String password, String email, String phone, String question, String answer, Integer role, Date createTime, Date updateTime) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.email = email;
        this.phone = phone;
        this.question = question;
        this.answer = answer;
        this.role = role;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table happymall_user
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_user.id
     *
     * @return the value of happymall_user.id
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_user.id
     *
     * @param id the value for happymall_user.id
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_user.username
     *
     * @return the value of happymall_user.username
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_user.username
     *
     * @param username the value for happymall_user.username
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_user.password
     *
     * @return the value of happymall_user.password
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_user.password
     *
     * @param password the value for happymall_user.password
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_user.email
     *
     * @return the value of happymall_user.email
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_user.email
     *
     * @param email the value for happymall_user.email
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_user.phone
     *
     * @return the value of happymall_user.phone
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_user.phone
     *
     * @param phone the value for happymall_user.phone
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_user.question
     *
     * @return the value of happymall_user.question
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_user.question
     *
     * @param question the value for happymall_user.question
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_user.answer
     *
     * @return the value of happymall_user.answer
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_user.answer
     *
     * @param answer the value for happymall_user.answer
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_user.role
     *
     * @return the value of happymall_user.role
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_user.role
     *
     * @param role the value for happymall_user.role
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_user.create_time
     *
     * @return the value of happymall_user.create_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_user.create_time
     *
     * @param createTime the value for happymall_user.create_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column happymall_user.update_time
     *
     * @return the value of happymall_user.update_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column happymall_user.update_time
     *
     * @param updateTime the value for happymall_user.update_time
     *
     * @mbggenerated Sun Oct 08 14:03:47 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}